import type { Metadata } from "next";
import { Poppins, Geist_Mono } from "next/font/google"; // Import Poppins, keep Geist_Mono
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";

// Instantiate Poppins
const poppins = Poppins({
  variable: "--font-sans", // Use standard --font-sans variable
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Include desired weights
});

// Keep Geist Mono if needed, or replace with a Poppins-compatible mono font
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* Update body className to use Poppins variable */}
      <body className={`${poppins.variable} ${geistMono.variable} font-sans antialiased`}> {/* Added font-sans base class */}
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
